#!/bin/bash

git submodule add ssh://git@github.com/CodeEditorLand/ApplicationinsightsLand.git Application/ApplicationinsightsLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureBoardsLand.git Application/AzureBoardsLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureDatalakeToolsForLand.git Application/AzureDatalakeToolsForLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureIotDeveloperKit.git Application/AzureIotDeveloperKit
git submodule add ssh://git@github.com/CodeEditorLand/AzurePipelinesLand.git Application/AzurePipelinesLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureReposLand.git Application/AzureReposLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureStreamAnalyticsInLand.git Application/AzureStreamAnalyticsInLand
git submodule add ssh://git@github.com/CodeEditorLand/Codetour.git Application/Codetour
git submodule add ssh://git@github.com/CodeEditorLand/ComposeLanguageService.git Application/ComposeLanguageService
git submodule add ssh://git@github.com/CodeEditorLand/DeoptexplorerLand.git Application/DeoptexplorerLand
git submodule add ssh://git@github.com/CodeEditorLand/DevSkim.git Application/DevSkim
git submodule add ssh://git@github.com/CodeEditorLand/DevSkimLandPlugin.git Application/DevSkimLandPlugin
git submodule add ssh://git@github.com/CodeEditorLand/DstoolkitDevcontainers.git Application/DstoolkitDevcontainers
git submodule add ssh://git@github.com/CodeEditorLand/Gnls.git Application/Gnls
git submodule add ssh://git@github.com/CodeEditorLand/Land.git Application/Land
git submodule add ssh://git@github.com/CodeEditorLand/LandAnacondaExtensionPack.git Application/LandAnacondaExtensionPack
git submodule add ssh://git@github.com/CodeEditorLand/LandAnycode.git Application/LandAnycode
git submodule add ssh://git@github.com/CodeEditorLand/LandApimanagement.git Application/LandApimanagement
git submodule add ssh://git@github.com/CodeEditorLand/LandAppcenter.git Application/LandAppcenter
git submodule add ssh://git@github.com/CodeEditorLand/LandArduino.git Application/LandArduino
git submodule add ssh://git@github.com/CodeEditorLand/LandAsa.git Application/LandAsa
git submodule add ssh://git@github.com/CodeEditorLand/LandAtomKeybindings.git Application/LandAtomKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandAutopep8.git Application/LandAutopep8
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureAccount.git Application/LandAzureAccount
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureappservice.git Application/LandAzureappservice
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurearmtools.git Application/LandAzurearmtools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureAutomation.git Application/LandAzureAutomation
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureBlockchainEthereum.git Application/LandAzureBlockchainEthereum
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecache.git Application/LandAzurecache
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecli.git Application/LandAzurecli
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecognitivesearch.git Application/LandAzurecognitivesearch
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecontainerapps.git Application/LandAzurecontainerapps
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureeventgrid.git Application/LandAzureeventgrid
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurefunctions.git Application/LandAzurefunctions
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureFunctionsRemoteWebExtension.git Application/LandAzureFunctionsRemoteWebExtension
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurehealthcareapisTools.git Application/LandAzurehealthcareapisTools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureIotEdge.git Application/LandAzureIotEdge
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureIotToolkit.git Application/LandAzureIotToolkit
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureIotTools.git Application/LandAzureIotTools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurelogicapps.git Application/LandAzurelogicapps
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurePack.git Application/LandAzurePack
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureresourcegroups.git Application/LandAzureresourcegroups
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureserverlesspack.git Application/LandAzureserverlesspack
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurespringcloud.git Application/LandAzurespringcloud
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurestaticwebapps.git Application/LandAzurestaticwebapps
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurestorage.git Application/LandAzurestorage
git submodule add ssh://git@github.com/CodeEditorLand/LandAzuretools.git Application/LandAzuretools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurevirtualmachines.git Application/LandAzurevirtualmachines
git submodule add ssh://git@github.com/CodeEditorLand/LandBackspace.git Application/LandBackspace
git submodule add ssh://git@github.com/CodeEditorLand/LandBisect.git Application/LandBisect
git submodule add ssh://git@github.com/CodeEditorLand/LandBlackFormatter.git Application/LandBlackFormatter
git submodule add ssh://git@github.com/CodeEditorLand/LandBracketsKeybindings.git Application/LandBracketsKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandBracketsPack.git Application/LandBracketsPack
git submodule add ssh://git@github.com/CodeEditorLand/LandCdp.git Application/LandCdp
git submodule add ssh://git@github.com/CodeEditorLand/LandCdpProxy.git Application/LandCdpProxy
git submodule add ssh://git@github.com/CodeEditorLand/LandChromeDebug.git Application/LandChromeDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandChromeDebugCore.git Application/LandChromeDebugCore
git submodule add ssh://git@github.com/CodeEditorLand/LandCmakeTools.git Application/LandCmakeTools
git submodule add ssh://git@github.com/CodeEditorLand/LandCmakeToolsApi.git Application/LandCmakeToolsApi
git submodule add ssh://git@github.com/CodeEditorLand/LandCodicons.git Application/LandCodicons
git submodule add ssh://git@github.com/CodeEditorLand/LandComment.git Application/LandComment
git submodule add ssh://git@github.com/CodeEditorLand/LandCopilotRelease.git Application/LandCopilotRelease
git submodule add ssh://git@github.com/CodeEditorLand/LandCordova.git Application/LandCordova
git submodule add ssh://git@github.com/CodeEditorLand/LandCosmosdb.git Application/LandCosmosdb
git submodule add ssh://git@github.com/CodeEditorLand/LandCosmosdbgraph.git Application/LandCosmosdbgraph
git submodule add ssh://git@github.com/CodeEditorLand/LandCourseSample.git Application/LandCourseSample
git submodule add ssh://git@github.com/CodeEditorLand/LandCpptools.git Application/LandCpptools
git submodule add ssh://git@github.com/CodeEditorLand/LandCpptoolsApi.git Application/LandCpptoolsApi
git submodule add ssh://git@github.com/CodeEditorLand/LandCss.git Application/LandCss
git submodule add ssh://git@github.com/CodeEditorLand/LandCssLanguageservice.git Application/LandCssLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandCustomData.git Application/LandCustomData
git submodule add ssh://git@github.com/CodeEditorLand/LandDapr.git Application/LandDapr
git submodule add ssh://git@github.com/CodeEditorLand/LandDataWrangler.git Application/LandDataWrangler
git submodule add ssh://git@github.com/CodeEditorLand/LandDebugadapterNode.git Application/LandDebugadapterNode
git submodule add ssh://git@github.com/CodeEditorLand/LandDeployAzure.git Application/LandDeployAzure
git submodule add ssh://git@github.com/CodeEditorLand/LandDevChromeLauncher.git Application/LandDevChromeLauncher
git submodule add ssh://git@github.com/CodeEditorLand/LandDevContainers.git Application/LandDevContainers
git submodule add ssh://git@github.com/CodeEditorLand/LandDiagnosticTools.git Application/LandDiagnosticTools
git submodule add ssh://git@github.com/CodeEditorLand/LandDiscussions.git Application/LandDiscussions
git submodule add ssh://git@github.com/CodeEditorLand/LandDocker.git Application/LandDocker
git submodule add ssh://git@github.com/CodeEditorLand/LandDockerExtensibility.git Application/LandDockerExtensibility
git submodule add ssh://git@github.com/CodeEditorLand/LandDocs.git Application/LandDocs
git submodule add ssh://git@github.com/CodeEditorLand/LandDocsArchive.git Application/LandDocsArchive
git submodule add ssh://git@github.com/CodeEditorLand/LandDocsAuthoring.git Application/LandDocsAuthoring
git submodule add ssh://git@github.com/CodeEditorLand/LandDotnettools.git Application/LandDotnettools
git submodule add ssh://git@github.com/CodeEditorLand/LandDtdl.git Application/LandDtdl
git submodule add ssh://git@github.com/CodeEditorLand/LandDts.git Application/LandDts
git submodule add ssh://git@github.com/CodeEditorLand/LandDwarfDebugging.git Application/LandDwarfDebugging
git submodule add ssh://git@github.com/CodeEditorLand/LandDwarfDebuggingExt.git Application/LandDwarfDebuggingExt
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDebug.git Application/LandEdgeDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDebug2.git Application/LandEdgeDebug2
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDevtools.git Application/LandEdgeDevtools
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDevtoolsNetwork.git Application/LandEdgeDevtoolsNetwork
git submodule add ssh://git@github.com/CodeEditorLand/LandEditorconfig.git Application/LandEditorconfig
git submodule add ssh://git@github.com/CodeEditorLand/LandEmbeddedTools.git Application/LandEmbeddedTools
git submodule add ssh://git@github.com/CodeEditorLand/LandEmmetHelper.git Application/LandEmmetHelper
git submodule add ssh://git@github.com/CodeEditorLand/LandEmmetLegacy.git Application/LandEmmetLegacy
git submodule add ssh://git@github.com/CodeEditorLand/LandEslint.git Application/LandEslint
git submodule add ssh://git@github.com/CodeEditorLand/LandExplorerCommand.git Application/LandExplorerCommand
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionLand.git Application/LandExtensionLand
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionRecommender.git Application/LandExtensionRecommender
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionSamples.git Application/LandExtensionSamples
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionTelemetry.git Application/LandExtensionTelemetry
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionTestRunner.git Application/LandExtensionTestRunner
git submodule add ssh://git@github.com/CodeEditorLand/LandFigmaIcons.git Application/LandFigmaIcons
git submodule add ssh://git@github.com/CodeEditorLand/LandFigmaToolkit.git Application/LandFigmaToolkit
git submodule add ssh://git@github.com/CodeEditorLand/LandFileDownloader.git Application/LandFileDownloader
git submodule add ssh://git@github.com/CodeEditorLand/LandFileDownloaderApi.git Application/LandFileDownloaderApi
git submodule add ssh://git@github.com/CodeEditorLand/LandFilewatcherWindows.git Application/LandFilewatcherWindows
git submodule add ssh://git@github.com/CodeEditorLand/LandFlake8.git Application/LandFlake8
git submodule add ssh://git@github.com/CodeEditorLand/LandGather.git Application/LandGather
git submodule add ssh://git@github.com/CodeEditorLand/LandGeneratorCode.git Application/LandGeneratorCode
git submodule add ssh://git@github.com/CodeEditorLand/LandGeneratorCodeJavascript.git Application/LandGeneratorCodeJavascript
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubIssueNotebooks.git Application/LandGithubIssueNotebooks
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubIssuesPrs.git Application/LandGithubIssuesPrs
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubTriageActions.git Application/LandGithubTriageActions
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubTriageExtension.git Application/LandGithubTriageExtension
git submodule add ssh://git@github.com/CodeEditorLand/LandGo.git Application/LandGo
git submodule add ssh://git@github.com/CodeEditorLand/LandGradle.git Application/LandGradle
git submodule add ssh://git@github.com/CodeEditorLand/LandGrammarUpdater.git Application/LandGrammarUpdater
git submodule add ssh://git@github.com/CodeEditorLand/LandGulpElectron.git Application/LandGulpElectron
git submodule add ssh://git@github.com/CodeEditorLand/LandHexeditor.git Application/LandHexeditor
git submodule add ssh://git@github.com/CodeEditorLand/LandHtmlhint.git Application/LandHtmlhint
git submodule add ssh://git@github.com/CodeEditorLand/LandHtmlLanguageservice.git Application/LandHtmlLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandHtmltagwrap.git Application/LandHtmltagwrap
git submodule add ssh://git@github.com/CodeEditorLand/LandHydrate.git Application/LandHydrate
git submodule add ssh://git@github.com/CodeEditorLand/LandIcons.git Application/LandIcons
git submodule add ssh://git@github.com/CodeEditorLand/LandIconvLiteUmd.git Application/LandIconvLiteUmd
git submodule add ssh://git@github.com/CodeEditorLand/LandIosWebDebug.git Application/LandIosWebDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandIotWorkbench.git Application/LandIotWorkbench
git submodule add ssh://git@github.com/CodeEditorLand/LandIsort.git Application/LandIsort
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaDebug.git Application/LandJavaDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaDependency.git Application/LandJavaDependency
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaInstaller.git Application/LandJavaInstaller
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaPack.git Application/LandJavaPack
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaTest.git Application/LandJavaTest
git submodule add ssh://git@github.com/CodeEditorLand/LandJsAtomGrammar.git Application/LandJsAtomGrammar
git submodule add ssh://git@github.com/CodeEditorLand/LandJscs.git Application/LandJscs
git submodule add ssh://git@github.com/CodeEditorLand/LandJsDebug.git Application/LandJsDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandJsDebugBrowsers.git Application/LandJsDebugBrowsers
git submodule add ssh://git@github.com/CodeEditorLand/LandJsDebugCompanion.git Application/LandJsDebugCompanion
git submodule add ssh://git@github.com/CodeEditorLand/LandJshint.git Application/LandJshint
git submodule add ssh://git@github.com/CodeEditorLand/LandJSON.tmLanguage.git CodeEditorLand/Application.tmLanguage
git submodule add ssh://git@github.com/CodeEditorLand/LandJsonLanguageservice.git Application/LandJsonLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandJsProfileVisualizer.git Application/LandJsProfileVisualizer
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyter.git Application/LandJupyter
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterCellTags.git Application/LandJupyterCellTags
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterHub.git Application/LandJupyterHub
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterIpywidgets.git Application/LandJupyterIpywidgets
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterKeymap.git Application/LandJupyterKeymap
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterLspMiddleware.git Application/LandJupyterLspMiddleware
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterPowertoys.git Application/LandJupyterPowertoys
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterSlideshow.git Application/LandJupyterSlideshow
git submodule add ssh://git@github.com/CodeEditorLand/LandJvmTools.git Application/LandJvmTools
git submodule add ssh://git@github.com/CodeEditorLand/LandL10n.git Application/LandL10n
git submodule add ssh://git@github.com/CodeEditorLand/LandLanguagedetection.git Application/LandLanguagedetection
git submodule add ssh://git@github.com/CodeEditorLand/LandLanguageserverNode.git Application/LandLanguageserverNode
git submodule add ssh://git@github.com/CodeEditorLand/LandLanguageserverProtocolFoldingprovider.git Application/LandLanguageserverProtocolFoldingprovider
git submodule add ssh://git@github.com/CodeEditorLand/LandLaTeX.git Application/LandLaTeX
git submodule add ssh://git@github.com/CodeEditorLand/LandLinuxBuildAgent.git Application/LandLinuxBuildAgent
git submodule add ssh://git@github.com/CodeEditorLand/LandLivepreview.git Application/LandLivepreview
git submodule add ssh://git@github.com/CodeEditorLand/LandLoader.git Application/LandLoader
git submodule add ssh://git@github.com/CodeEditorLand/LandLoc.git Application/LandLoc
git submodule add ssh://git@github.com/CodeEditorLand/LandLocDeprecated.git Application/LandLocDeprecated
git submodule add ssh://git@github.com/CodeEditorLand/LandLombok.git Application/LandLombok
git submodule add ssh://git@github.com/CodeEditorLand/LandLsifExtension.git Application/LandLsifExtension
git submodule add ssh://git@github.com/CodeEditorLand/LandMakecode.git Application/LandMakecode
git submodule add ssh://git@github.com/CodeEditorLand/LandMakefileTools.git Application/LandMakefileTools
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownItKatex.git Application/LandMarkdownItKatex
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownLanguageservice.git Application/LandMarkdownLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownNotebook.git Application/LandMarkdownNotebook
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownTmGrammar.git Application/LandMarkdownTmGrammar
git submodule add ssh://git@github.com/CodeEditorLand/LandMaven.git Application/LandMaven
git submodule add ssh://git@github.com/CodeEditorLand/LandMDTools.git Application/LandMDTools
git submodule add ssh://git@github.com/CodeEditorLand/LandMezzurite.git Application/LandMezzurite
git submodule add ssh://git@github.com/CodeEditorLand/LandMinimist.git Application/LandMinimist
git submodule add ssh://git@github.com/CodeEditorLand/LandMockDebug.git Application/LandMockDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandMongodb.git Application/LandMongodb
git submodule add ssh://git@github.com/CodeEditorLand/LandMonoDebug.git Application/LandMonoDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandMssql.git Application/LandMssql
git submodule add ssh://git@github.com/CodeEditorLand/LandMypy.git Application/LandMypy
git submodule add ssh://git@github.com/CodeEditorLand/LandNls.git Application/LandNls
git submodule add ssh://git@github.com/CodeEditorLand/LandNlsDev.git Application/LandNlsDev
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeAzurePack.git Application/LandNodeAzurePack
git submodule add ssh://git@github.com/CodeEditorLand/LandNodebook.git Application/LandNodebook
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeDebug.git Application/LandNodeDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeDebug2.git Application/LandNodeDebug2
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeSqlite3.git Application/LandNodeSqlite3
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookErrorOverlay.git Application/LandNotebookErrorOverlay
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookRenderers.git Application/LandNotebookRenderers
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookRendererStarter.git Application/LandNotebookRendererStarter
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookTestdata.git Application/LandNotebookTestdata
git submodule add ssh://git@github.com/CodeEditorLand/LandNotepadplusplusKeybindings.git Application/LandNotepadplusplusKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandNpmScripts.git Application/LandNpmScripts
git submodule add ssh://git@github.com/CodeEditorLand/LandOcticonsFont.git Application/LandOcticonsFont
git submodule add ssh://git@github.com/CodeEditorLand/LandOnedriveBrowser.git Application/LandOnedriveBrowser
git submodule add ssh://git@github.com/CodeEditorLand/LandOniguruma.git Application/LandOniguruma
git submodule add ssh://git@github.com/CodeEditorLand/LandOpensslPrebuilt.git Application/LandOpensslPrebuilt
git submodule add ssh://git@github.com/CodeEditorLand/LandPerf.git Application/LandPerf
git submodule add ssh://git@github.com/CodeEditorLand/LandPerfBot.git Application/LandPerfBot
git submodule add ssh://git@github.com/CodeEditorLand/LandPlatformSpecificSample.git Application/LandPlatformSpecificSample
git submodule add ssh://git@github.com/CodeEditorLand/LandPolicyWatcher.git Application/LandPolicyWatcher
git submodule add ssh://git@github.com/CodeEditorLand/LandPostgresql.git Application/LandPostgresql
git submodule add ssh://git@github.com/CodeEditorLand/LandPowerquery.git Application/LandPowerquery
git submodule add ssh://git@github.com/CodeEditorLand/LandPowerquerySdk.git Application/LandPowerquerySdk
git submodule add ssh://git@github.com/CodeEditorLand/LandProxyAgent.git Application/LandProxyAgent
git submodule add ssh://git@github.com/CodeEditorLand/LandPullRequestGithub.git Application/LandPullRequestGithub
git submodule add ssh://git@github.com/CodeEditorLand/LandPwaAnalyzer.git Application/LandPwaAnalyzer
git submodule add ssh://git@github.com/CodeEditorLand/LandPylint.git Application/LandPylint
git submodule add ssh://git@github.com/CodeEditorLand/LandPython.git Application/LandPython
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonDebugger.git Application/LandPythonDebugger
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonDevicesimulator.git Application/LandPythonDevicesimulator
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonDsExtensionPack.git Application/LandPythonDsExtensionPack
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonInstaller.git Application/LandPythonInstaller
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonToolsExtensionTemplate.git Application/LandPythonToolsExtensionTemplate
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonWebWasm.git Application/LandPythonWebWasm
git submodule add ssh://git@github.com/CodeEditorLand/LandReactNative.git Application/LandReactNative
git submodule add ssh://git@github.com/CodeEditorLand/LandReactSample.git Application/LandReactSample
git submodule add ssh://git@github.com/CodeEditorLand/LandRecipes.git Application/LandRecipes
git submodule add ssh://git@github.com/CodeEditorLand/LandReferencesView.git Application/LandReferencesView
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteRelease.git Application/LandRemoteRelease
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteRepositoriesGithub.git Application/LandRemoteRepositoriesGithub
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryCpp.git Application/LandRemoteTryCpp
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryDotnet.git Application/LandRemoteTryDotnet
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryGo.git Application/LandRemoteTryGo
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryJava.git Application/LandRemoteTryJava
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryNode.git Application/LandRemoteTryNode
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryPhp.git Application/LandRemoteTryPhp
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryPython.git Application/LandRemoteTryPython
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryRust.git Application/LandRemoteTryRust
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTrySqlserver.git Application/LandRemoteTrySqlserver
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteWslRecommender.git Application/LandRemoteWslRecommender
git submodule add ssh://git@github.com/CodeEditorLand/LandResharperKeybindings.git Application/LandResharperKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandRipgrep.git Application/LandRipgrep
git submodule add ssh://git@github.com/CodeEditorLand/LandRussh.git Application/LandRussh
git submodule add ssh://git@github.com/CodeEditorLand/LandSamples.git Application/LandSamples
git submodule add ssh://git@github.com/CodeEditorLand/LandSCMBuilders.git Application/LandSCMBuilders
git submodule add ssh://git@github.com/CodeEditorLand/LandSecretServiceRs.git Application/LandSecretServiceRs
git submodule add ssh://git@github.com/CodeEditorLand/LandSelfhostTestProvider.git Application/LandSelfhostTestProvider
git submodule add ssh://git@github.com/CodeEditorLand/LandSerialMonitor.git Application/LandSerialMonitor
git submodule add ssh://git@github.com/CodeEditorLand/LandServiceFabricReliableServices.git Application/LandServiceFabricReliableServices
git submodule add ssh://git@github.com/CodeEditorLand/LandServiceStatus.git Application/LandServiceStatus
git submodule add ssh://git@github.com/CodeEditorLand/LandSimpleJupyterNotebook.git Application/LandSimpleJupyterNotebook
git submodule add ssh://git@github.com/CodeEditorLand/LandSmoketestCheck.git Application/LandSmoketestCheck
git submodule add ssh://git@github.com/CodeEditorLand/LandSmoketestExpress.git Application/LandSmoketestExpress
git submodule add ssh://git@github.com/CodeEditorLand/LandspacesQuickstart.git Application/LandspacesQuickstart
git submodule add ssh://git@github.com/CodeEditorLand/LandSpellCheck.git Application/LandSpellCheck
git submodule add ssh://git@github.com/CodeEditorLand/LandSpringBootDashboard.git Application/LandSpringBootDashboard
git submodule add ssh://git@github.com/CodeEditorLand/LandSpringInitializr.git Application/LandSpringInitializr
git submodule add ssh://git@github.com/CodeEditorLand/LandStac.git Application/LandStac
git submodule add ssh://git@github.com/CodeEditorLand/LandSublimeKeybindings.git Application/LandSublimeKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandTasAngular.git Application/LandTasAngular
git submodule add ssh://git@github.com/CodeEditorLand/LandTasExpress.git Application/LandTasExpress
git submodule add ssh://git@github.com/CodeEditorLand/LandTasVue.git Application/LandTasVue
git submodule add ssh://git@github.com/CodeEditorLand/LandTeam.git Application/LandTeam
git submodule add ssh://git@github.com/CodeEditorLand/LandTelemetryExtractor.git Application/LandTelemetryExtractor
git submodule add ssh://git@github.com/CodeEditorLand/LandTensorboard.git Application/LandTensorboard
git submodule add ssh://git@github.com/CodeEditorLand/LandTest.git Application/LandTest
git submodule add ssh://git@github.com/CodeEditorLand/LandTestAdapterConverter.git Application/LandTestAdapterConverter
git submodule add ssh://git@github.com/CodeEditorLand/LandTestCli.git Application/LandTestCli
git submodule add ssh://git@github.com/CodeEditorLand/Landtestcover.git Application/Landtestcover
git submodule add ssh://git@github.com/CodeEditorLand/LandTestWeb.git Application/LandTestWeb
git submodule add ssh://git@github.com/CodeEditorLand/LandTextbuffer.git Application/LandTextbuffer
git submodule add ssh://git@github.com/CodeEditorLand/LandTextmate.git Application/LandTextmate
git submodule add ssh://git@github.com/CodeEditorLand/LandThemeColorConsumer.git Application/LandThemeColorConsumer
git submodule add ssh://git@github.com/CodeEditorLand/LandThemes.git Application/LandThemes
git submodule add ssh://git@github.com/CodeEditorLand/LandThemeTester.git Application/LandThemeTester
git submodule add ssh://git@github.com/CodeEditorLand/LandTipsAndTricks.git Application/LandTipsAndTricks
git submodule add ssh://git@github.com/CodeEditorLand/LandTmdl.git Application/LandTmdl
git submodule add ssh://git@github.com/CodeEditorLand/LandToolsForAi.git Application/LandToolsForAi
git submodule add ssh://git@github.com/CodeEditorLand/LandTslint.git Application/LandTslint
git submodule add ssh://git@github.com/CodeEditorLand/LandTsPackageManager.git Application/LandTsPackageManager
git submodule add ssh://git@github.com/CodeEditorLand/LandTsTslint.git Application/LandTsTslint
git submodule add ssh://git@github.com/CodeEditorLand/LandTye.git Application/LandTye
git submodule add ssh://git@github.com/CodeEditorLand/LandTypescriptNext.git Application/LandTypescriptNext
git submodule add ssh://git@github.com/CodeEditorLand/LandTypescriptTslintPlugin.git Application/LandTypescriptTslintPlugin
git submodule add ssh://git@github.com/CodeEditorLand/LandUri.git Application/LandUri
git submodule add ssh://git@github.com/CodeEditorLand/LandV8HeapTools.git Application/LandV8HeapTools
git submodule add ssh://git@github.com/CodeEditorLand/LandVsce.git Application/LandVsce
git submodule add ssh://git@github.com/CodeEditorLand/LandVsKeybindings.git Application/LandVsKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandWasm.git Application/LandWasm
git submodule add ssh://git@github.com/CodeEditorLand/LandWebPlayground.git Application/LandWebPlayground
git submodule add ssh://git@github.com/CodeEditorLand/LandWebviewUiToolkit.git Application/LandWebviewUiToolkit
git submodule add ssh://git@github.com/CodeEditorLand/LandWebviewUiToolkitSamples.git Application/LandWebviewUiToolkitSamples
git submodule add ssh://git@github.com/CodeEditorLand/LandWiki.git Application/LandWiki
git submodule add ssh://git@github.com/CodeEditorLand/LandWin32AppContainerTokens.git Application/LandWin32AppContainerTokens
git submodule add ssh://git@github.com/CodeEditorLand/LandWindowsCaCerts.git Application/LandWindowsCaCerts
git submodule add ssh://git@github.com/CodeEditorLand/LandWindowsProcessTree.git Application/LandWindowsProcessTree
git submodule add ssh://git@github.com/CodeEditorLand/LandWindowsRegistry.git Application/LandWindowsRegistry
git submodule add ssh://git@github.com/CodeEditorLand/LandWinsta11er.git Application/LandWinsta11er
git submodule add ssh://git@github.com/CodeEditorLand/LandWordcount.git Application/LandWordcount
git submodule add ssh://git@github.com/CodeEditorLand/LandZeromq.git Application/LandZeromq
git submodule add ssh://git@github.com/CodeEditorLand/Linkcheckermd.git Application/Linkcheckermd
git submodule add ssh://git@github.com/CodeEditorLand/MonacoEditor.git Application/MonacoEditor
git submodule add ssh://git@github.com/CodeEditorLand/NodeRequestLight.git Application/NodeRequestLight
git submodule add ssh://git@github.com/CodeEditorLand/Oniguruma.git Application/Oniguruma
git submodule add ssh://git@github.com/CodeEditorLand/PlaywrightLand.git Application/PlaywrightLand
git submodule add ssh://git@github.com/CodeEditorLand/PowerplatformLand.git Application/PowerplatformLand
git submodule add ssh://git@github.com/CodeEditorLand/PowerplatformLandLab.git Application/PowerplatformLandLab
git submodule add ssh://git@github.com/CodeEditorLand/PSDocsLand.git Application/PSDocsLand
git submodule add ssh://git@github.com/CodeEditorLand/PSRuleLand.git Application/PSRuleLand
git submodule add ssh://git@github.com/CodeEditorLand/Pvscbot.git Application/Pvscbot
git submodule add ssh://git@github.com/CodeEditorLand/PythonSampleLandDjangoTutorial.git Application/PythonSampleLandDjangoTutorial
git submodule add ssh://git@github.com/CodeEditorLand/PythonSampleLandFastapiTutorial.git Application/PythonSampleLandFastapiTutorial
git submodule add ssh://git@github.com/CodeEditorLand/PythonSampleLandFlaskTutorial.git Application/PythonSampleLandFlaskTutorial
git submodule add ssh://git@github.com/CodeEditorLand/SarifLandExtension.git Application/SarifLandExtension
git submodule add ssh://git@github.com/CodeEditorLand/ScopestudioLand.git Application/ScopestudioLand
git submodule add ssh://git@github.com/CodeEditorLand/SynapseLand.git Application/SynapseLand
git submodule add ssh://git@github.com/CodeEditorLand/TestBed.git Application/TestBed
git submodule add ssh://git@github.com/CodeEditorLand/ThemeConverterForVs.git Application/ThemeConverterForVs
git submodule add ssh://git@github.com/CodeEditorLand/TypeScriptLandExtensions.git Application/TypeScriptLandExtensions
