#!/bin/bash

JSON=$(< package.json)

JSON=$(echo "$JSON" | \jq -S --tab "del(\
	.author,\
	.bugs,\
	.categories,\
	.distro,\
	.engines,\
	.eslintConfig,\
	.fix,\
	.homepage,\
	.keywords,\
	.license,\
	.packageManager,\
	.peerDependencies,\
	.prettier,\
	.private,\
	.publishConfig,\
	.publisher,\
	.repository,\
	.scripts.[\"check:apply\"],\
	.scripts.[\"fmt:js\"],\
	.scripts.[\"format-check\"],\
	.scripts.[\"format:check\"],\
	.scripts.[\"format:eslint\"],\
	.scripts.[\"format:prettier\"],\
	.scripts.[\"format:stylelint\"],\
	.scripts.[\"lint-fix:format\"],\
	.scripts.[\"lint-fix:js\"],\
	.scripts.[\"lint-fix:styles\"],\
	.scripts.[\"lint-fix\"],\
	.scripts.[\"lint-format\"],\
	.scripts.[\"lint:client\"],\
	.scripts.[\"lint:eslint\"],\
	.scripts.[\"lint:fix:prettier\"],\
	.scripts.[\"lint:fix\"],\
	.scripts.[\"lint:format\"],\
	.scripts.[\"lint:js\"],\
	.scripts.[\"lint:prettier\"],\
	.scripts.[\"lint:scripts\"],\
	.scripts.[\"lint:server\"],\
	.scripts.[\"lint:styles\"],\
	.scripts.[\"lint:tsc\"],\
	.scripts.[\"lint:types\"],\
	.scripts.[\"prettier-fix\"],\
	.scripts.[\"test:eslint-rules\"],\
	.scripts.[\"test:fmt\"],\
	.scripts.[\"test:lint\"],\
	.scripts.[\"vscode:prepublish\"],\
	.scripts.bump,\
	.scripts.check,\
	.scripts.eslint,\
	.scripts.fmt,\
	.scripts.format,\
	.scripts.lint,\
	.scripts.nodemon,\
	.scripts.package,\
	.scripts.posttest,\
	.scripts.prepublish,\
	.scripts.pretest,\
	.scripts.prettier,\
	.scripts.stylelint,\
	.scripts.test,\
	.scripts.tsc,\
	.scripts.tslint,\
	.scripts.typecheck,\
	.scripts.watch,\
	.tags,\
	.test,\
	.tslint,\
	.type,\
	.version\
)")

echo "$JSON" >| package.json

Omit=(
	"@babel/core"
	"@babel/eslint-config-internal"
	"@babel/eslint-parser"
	"@babel/eslint-plugin-development"
	"@babel/eslint-plugin-development-internal"
	"@babel/plugin-transform-runtime"
	"@babel/preset-env"
	"@babel/preset-react"
	"@babel/preset-typescript"
	"@babel/runtime"
	"@electron-forge/cli"
	"@electron-forge/maker-deb"
	"@electron-forge/maker-rpm"
	"@electron-forge/maker-squirrel"
	"@electron-forge/maker-zip"
	"@electron/get"
	"@eslint/eslintrc"
	"@eslint/js"
	"@fluentui/react"
	"@iconify/react"
	"@microsoft/eslint-config-azuretools"
	"@microsoft/eslint-config-fast-dna"
	"@microsoft/vscode-azext-azureappservice"
	"@microsoft/vscode-azext-azureappsettings"
	"@microsoft/vscode-azext-azureutils"
	"@microsoft/vscode-azext-dev"
	"@microsoft/vscode-azext-utils"
	"@microsoft/vscode-azureresources-api"
	"@microsoft/vscode-serial-monitor-api"
	"@mixer/parallel-prettier"
	"@nicolo-ribaudo/eslint-scope-5-internals"
	"@playform/document"
	"@playwright/browser-chromium"
	"@playwright/test"
	"@svgr/webpack"
	"@testing-library/react"
	"@types/copy-webpack-plugin"
	"@types/eslint"
	"@types/express"
	"@types/gulp"
	"@types/gulp-concat"
	"@types/gulp-filter"
	"@types/gulp-gzip"
	"@types/gulp-json-editor"
	"@types/gulp-rename"
	"@types/gulp-sourcemaps"
	"@types/gulp-svgmin"
	"@types/jest"
	"@types/mocha"
	"@types/react"
	"@types/react-dom"
	"@types/react-json-tree"
	"@types/react-redux"
	"@types/react-virtualized"
	"@types/sinon-test"
	"@types/terser-webpack-plugin"
	"@types/vscode"
	"@types/vscode-notebook-renderer"
	"@types/vscode-webview"
	"@types/webpack"
	"@types/webpack-env"
	"@typescript-eslint/eslint-plugin"
	"@typescript-eslint/eslint-plugin-tslint"
	"@typescript-eslint/experimental-utils"
	"@typescript-eslint/parser"
	"@typescript-eslint/utils"
	"@vitest/coverage-v8"
	"@vitest/ui"
	"@vscode/codicons"
	"@vscode/debugadapter"
	"@vscode/debugprotocol"
	"@vscode/emmet-helper"
	"@vscode/extension-telemetry"
	"@vscode/gulp-electron"
	"@vscode/iconv-lite-umd"
	"@vscode/js-debug-browsers"
	"@vscode/jupyter-extension"
	"@vscode/l10n"
	"@vscode/l10n-dev"
	"@vscode/markdown-it-katex"
	"@vscode/policy-watcher"
	"@vscode/proxy-agent"
	"@vscode/python-extension"
	"@vscode/ripgrep"
	"@vscode/spdlog"
	"@vscode/sqlite3"
	"@vscode/sudo-prompt"
	"@vscode/sync-api-client"
	"@vscode/sync-api-common"
	"@vscode/sync-api-service"
	"@vscode/telemetry-extractor"
	"@vscode/test-cli"
	"@vscode/test-electron"
	"@vscode/test-web"
	"@vscode/v8-heap-parser"
	"@vscode/vsce"
	"@vscode/vscode-languagedetection"
	"@vscode/vscode-perf"
	"@vscode/webview-ui-toolkit"
	"@vscode/windows-mutex"
	"@vscode/windows-process-tree"
	"@vscode/windows-registry"
	"@vue/eslint-config-standard"
	"@wdio/mocha-framework"
	"babel-jest"
	"babel-loader"
	"babel-plugin-named-asset-import"
	"babel-preset-react-app"
	"babel-preset-react-native"
	"case-sensitive-paths-webpack-plugin"
	"chromium-pickle-js"
	"clean-webpack-plugin"
	"copy-webpack-plugin"
	"electron"
	"eslint"
	"eslint-cli"
	"eslint-config-airbnb"
	"eslint-config-commonality"
	"eslint-config-next"
	"eslint-config-prettier"
	"eslint-config-react-app"
	"eslint-config-standard"
	"eslint-formatter-autolinkable-stylish"
	"eslint-formatter-codeframe"
	"eslint-import-resolver-node"
	"eslint-import-resolver-typescript"
	"eslint-plugin-filenames"
	"eslint-plugin-flowtype"
	"eslint-plugin-header"
	"eslint-plugin-html"
	"eslint-plugin-import"
	"eslint-plugin-jest"
	"eslint-plugin-jsdoc"
	"eslint-plugin-jsx-a11y"
	"eslint-plugin-license-header"
	"eslint-plugin-local"
	"eslint-plugin-local-rules"
	"eslint-plugin-n"
	"eslint-plugin-no-null"
	"eslint-plugin-no-only-tests"
	"eslint-plugin-node"
	"eslint-plugin-notice"
	"eslint-plugin-prefer-arrow"
	"eslint-plugin-prettier"
	"eslint-plugin-promise"
	"eslint-plugin-react"
	"eslint-plugin-react-hooks"
	"eslint-plugin-require-path-exists"
	"eslint-plugin-security"
	"eslint-plugin-simple-import-sort"
	"eslint-plugin-standard"
	"eslint-plugin-testing-library"
	"eslint-plugin-tslint"
	"eslint-plugin-unicorn"
	"eslint-plugin-unused-imports"
	"eslint-plugin-vue"
	"eslint-rule-composer"
	"eslint-scope"
	"eslint-utils"
	"eslint-visitor-keys"
	"express"
	"filemanager-webpack-plugin"
	"fork-ts-checker-webpack-plugin"
	"gulp"
	"gulp-azure-storage"
	"gulp-bom"
	"gulp-buffer"
	"gulp-chmod"
	"gulp-cli"
	"gulp-concat"
	"gulp-debug"
	"gulp-decompress"
	"gulp-eslint"
	"gulp-filter"
	"gulp-flatmap"
	"gulp-gunzip"
	"gulp-gzip"
	"gulp-istanbul"
	"gulp-json-editor"
	"gulp-merge-json"
	"gulp-mocha"
	"gulp-plumber"
	"gulp-preprocess"
	"gulp-rename"
	"gulp-replace"
	"gulp-sourcemaps"
	"gulp-svgmin"
	"gulp-symdest"
	"gulp-tslint"
	"gulp-typescript"
	"gulp-untar"
	"html-webpack-plugin"
	"husky"
	"istanbul-lib-coverage"
	"istanbul-lib-instrument"
	"istanbul-lib-report"
	"istanbul-lib-source-maps"
	"istanbul-reports"
	"jest"
	"jest-environment-node"
	"jest-pnp-resolver"
	"jest-resolve"
	"jest-watch-typeahead"
	"mocha"
	"mocha-junit-reporter"
	"mocha-multi-reporters"
	"node-polyfill-webpack-plugin"
	"optimize-css-assets-webpack-plugin"
	"playwright"
	"pnp-webpack-plugin"
	"preact"
	"prettier"
	"prettier-eslint"
	"prettier-eslint-cli"
	"prettier-plugin-svelte"
	"react"
	"react-app-polyfill"
	"react-bootstrap"
	"react-data-grid"
	"react-dev-utils"
	"react-dom"
	"react-redux"
	"react-svg-pan-zoom"
	"react-svgmt"
	"react-virtualized"
	"release-it"
	"sinon-test"
	"terser-webpack-plugin"
	"ts-jest"
	"ts-node"
	"tsconfig-paths-webpack-plugin"
	"tslint"
	"tslint-eslint-rules"
	"tslint-to-eslint-config"
	"vite-plugin-dts"
	"vitest"
	"vscode-azureextensiondev"
	"vscode-azurekudu"
	"vscode-cdp-proxy"
	"vscode-chrome-debug-core"
	"vscode-chrome-debug-core-testsupport"
	"vscode-css-languageservice"
	"vscode-extension-telemetry-wrapper"
	"vscode-extension-tester"
	"vscode-html-languageservice"
	"vscode-json-languageservice"
	"vscode-jsonrpc"
	"vscode-kubernetes-tools-api"
	"vscode-languageclient"
	"vscode-languageserver"
	"vscode-languageserver-textdocument"
	"vscode-languageserver-types"
	"vscode-markdown-languageservice"
	"vscode-nls"
	"vscode-nls-dev"
	"vscode-oniguruma"
	"vscode-regexpp"
	"vscode-tas-client"
	"vscode-textmate"
	"vscode-universal-bundler"
	"vscode-uri"
	"vscode-webhint"
	"vue"
	"vue-eslint-parser"
	"vue-i18n"
	"vue-router"
	"vue-server-renderer"
	"vue-tsc"
	"vuex"
	"webpack"
	"webpack-bundle-analyzer"
	"webpack-cli"
	"webpack-dev-server"
	"webpack-manifest-plugin"
	"webpack-merge"
	"webpack-stream"
	"workbox-webpack-plugin"
	"yeoman-environment"
	"yeoman-generator"
)

Key() {
	JSON=$(< package.json)

	for Dependency in "${Omit[@]}"; do
		JSON=$(echo "$JSON" | \jq -S --tab "del(\
			.[\"$1\"].[\"${Dependency}\"]\
		)")
	done

	echo "$JSON" >| package.json
}

Key "dependencies"
Key "devDependencies"
Key "peerDependencies"
Key "optionalDependencies"
