#!/bin/sh

# Context: CodeEditorLand/Application

mv ./applicationinsights-vscode ./applicationinsights-Land
mv ./azure-boards-vscode ./azure-boards-Land
mv ./azure-pipelines-vscode ./azure-pipelines-Land
mv ./azure-repos-vscode ./azure-repos-Land
mv ./AzureDatalakeToolsForVSCode ./AzureDatalakeToolsForLand
mv ./AzureStreamAnalyticsInVSCode ./AzureStreamAnalyticsInLand
mv ./deoptexplorer-vscode ./deoptexplorer-Land
mv ./DevSkim-VSCode-Plugin ./DevSkim-Land-Plugin
mv ./playwright-vscode ./playwright-Land
mv ./powerplatform-vscode ./powerplatform-Land
mv ./powerplatform-vscode-lab ./powerplatform-Land-lab
mv ./PSDocs-vscode ./PSDocs-Land
mv ./PSRule-vscode ./PSRule-Land
mv ./python-sample-vscode-django-tutorial ./python-sample-Land-django-tutorial
mv ./python-sample-vscode-fastapi-tutorial ./python-sample-Land-fastapi-tutorial
mv ./python-sample-vscode-flask-tutorial ./python-sample-Land-flask-tutorial
mv ./sarif-vscode-extension ./sarif-Land-extension
mv ./scopestudio-vscode ./scopestudio-Land
mv ./SynapseVSCode ./SynapseLand
mv ./TypeScript-VSCode-Extensions ./TypeScript-Land-Extensions
mv ./vscode ./Land
mv ./vscode-anaconda-extension-pack ./Land-anaconda-extension-pack
mv ./vscode-anycode ./Land-anycode
mv ./vscode-apimanagement ./Land-apimanagement
mv ./vscode-appcenter ./Land-appcenter
mv ./vscode-arduino ./Land-arduino
mv ./vscode-asa ./Land-asa
mv ./vscode-atom-keybindings ./Land-atom-keybindings
mv ./vscode-autopep8 ./Land-autopep8
mv ./vscode-azure-account ./Land-azure-account
mv ./vscode-azure-blockchain-ethereum ./Land-azure-blockchain-ethereum
mv ./vscode-azure-functions-remote-web-extension ./Land-azure-functions-remote-web-extension
mv ./vscode-azure-iot-edge ./Land-azure-iot-edge
mv ./vscode-azure-iot-toolkit ./Land-azure-iot-toolkit
mv ./vscode-azure-iot-tools ./Land-azure-iot-tools
mv ./vscode-azure-pack ./Land-azure-pack
mv ./vscode-azureappservice ./Land-azureappservice
mv ./vscode-azurearmtools ./Land-azurearmtools
mv ./vscode-azureAutomation ./Land-azureAutomation
mv ./vscode-azurecache ./Land-azurecache
mv ./vscode-azurecli ./Land-azurecli
mv ./vscode-azurecognitivesearch ./Land-azurecognitivesearch
mv ./vscode-azurecontainerapps ./Land-azurecontainerapps
mv ./vscode-azureeventgrid ./Land-azureeventgrid
mv ./vscode-azurefunctions ./Land-azurefunctions
mv ./vscode-azurehealthcareapis-tools ./Land-azurehealthcareapis-tools
mv ./vscode-azurelogicapps ./Land-azurelogicapps
mv ./vscode-azureresourcegroups ./Land-azureresourcegroups
mv ./vscode-azureserverlesspack ./Land-azureserverlesspack
mv ./vscode-azurespringcloud ./Land-azurespringcloud
mv ./vscode-azurestaticwebapps ./Land-azurestaticwebapps
mv ./vscode-azurestorage ./Land-azurestorage
mv ./vscode-azuretools ./Land-azuretools
mv ./vscode-azurevirtualmachines ./Land-azurevirtualmachines
mv ./vscode-backspace ./Land-backspace
mv ./vscode-bisect ./Land-bisect
mv ./vscode-black-formatter ./Land-black-formatter
mv ./vscode-brackets-keybindings ./Land-brackets-keybindings
mv ./vscode-brackets-pack ./Land-brackets-pack
mv ./vscode-cdp ./Land-cdp
mv ./vscode-cdp-proxy ./Land-cdp-proxy
mv ./vscode-chrome-debug ./Land-chrome-debug
mv ./vscode-chrome-debug-core ./Land-chrome-debug-core
mv ./vscode-cmake-tools ./Land-cmake-tools
mv ./vscode-cmake-tools-api ./Land-cmake-tools-api
mv ./vscode-codicons ./Land-codicons
mv ./vscode-comment ./Land-comment
mv ./vscode-copilot-release ./Land-copilot-release
mv ./vscode-cordova ./Land-cordova
mv ./vscode-cosmosdb ./Land-cosmosdb
mv ./vscode-cosmosdbgraph ./Land-cosmosdbgraph
mv ./vscode-course-sample ./Land-course-sample
mv ./vscode-cpptools ./Land-cpptools
mv ./vscode-cpptools-api ./Land-cpptools-api
mv ./vscode-css ./Land-css
mv ./vscode-css-languageservice ./Land-css-languageservice
mv ./vscode-custom-data ./Land-custom-data
mv ./vscode-dapr ./Land-dapr
mv ./vscode-data-wrangler ./Land-data-wrangler
mv ./vscode-debugadapter-node ./Land-debugadapter-node
mv ./vscode-deploy-azure ./Land-deploy-azure
mv ./vscode-dev-chrome-launcher ./Land-dev-chrome-launcher
mv ./vscode-dev-containers ./Land-dev-containers
mv ./vscode-diagnostic-tools ./Land-diagnostic-tools
mv ./vscode-discussions ./Land-discussions
mv ./vscode-docker ./Land-docker
mv ./vscode-docker-extensibility ./Land-docker-extensibility
mv ./vscode-docs ./Land-docs
mv ./vscode-docs-archive ./Land-docs-archive
mv ./vscode-docs-authoring ./Land-docs-authoring
mv ./vscode-dotnettools ./Land-dotnettools
mv ./vscode-dtdl ./Land-dtdl
mv ./vscode-dts ./Land-dts
mv ./vscode-dwarf-debugging ./Land-dwarf-debugging
mv ./vscode-dwarf-debugging-ext ./Land-dwarf-debugging-ext
mv ./vscode-edge-debug ./Land-edge-debug
mv ./vscode-edge-debug2 ./Land-edge-debug2
mv ./vscode-edge-devtools ./Land-edge-devtools
mv ./vscode-edge-devtools-network ./Land-edge-devtools-network
mv ./vscode-editorconfig ./Land-editorconfig
mv ./vscode-embedded-tools ./Land-embedded-tools
mv ./vscode-emmet-helper ./Land-emmet-helper
mv ./vscode-emmet-legacy ./Land-emmet-legacy
mv ./vscode-eslint ./Land-eslint
mv ./vscode-explorer-command ./Land-explorer-command
mv ./vscode-extension-recommender ./Land-extension-recommender
mv ./vscode-extension-samples ./Land-extension-samples
mv ./vscode-extension-telemetry ./Land-extension-telemetry
mv ./vscode-extension-test-runner ./Land-extension-test-runner
mv ./vscode-extension-vscode ./Land-extension-Land
mv ./vscode-figma-icons ./Land-figma-icons
mv ./vscode-figma-toolkit ./Land-figma-toolkit
mv ./vscode-file-downloader ./Land-file-downloader
mv ./vscode-file-downloader-api ./Land-file-downloader-api
mv ./vscode-filewatcher-windows ./Land-filewatcher-windows
mv ./vscode-flake8 ./Land-flake8
mv ./vscode-gather ./Land-gather
mv ./vscode-generator-code ./Land-generator-code
mv ./vscode-generator-code-javascript ./Land-generator-code-javascript
mv ./vscode-github-issue-notebooks ./Land-github-issue-notebooks
mv ./vscode-github-issues-prs ./Land-github-issues-prs
mv ./vscode-github-triage-actions ./Land-github-triage-actions
mv ./vscode-github-triage-extension ./Land-github-triage-extension
mv ./vscode-go ./Land-go
mv ./vscode-gradle ./Land-gradle
mv ./vscode-grammar-updater ./Land-grammar-updater
mv ./vscode-gulp-electron ./Land-gulp-electron
mv ./vscode-hexeditor ./Land-hexeditor
mv ./vscode-html-languageservice ./Land-html-languageservice
mv ./vscode-htmlhint ./Land-htmlhint
mv ./vscode-htmltagwrap ./Land-htmltagwrap
mv ./vscode-hydrate ./Land-hydrate
mv ./vscode-icons ./Land-icons
mv ./vscode-iconv-lite-umd ./Land-iconv-lite-umd
mv ./vscode-ios-web-debug ./Land-ios-web-debug
mv ./vscode-iot-workbench ./Land-iot-workbench
mv ./vscode-isort ./Land-isort
mv ./vscode-java-debug ./Land-java-debug
mv ./vscode-java-dependency ./Land-java-dependency
mv ./vscode-java-installer ./Land-java-installer
mv ./vscode-java-pack ./Land-java-pack
mv ./vscode-java-test ./Land-java-test
mv ./vscode-js-atom-grammar ./Land-js-atom-grammar
mv ./vscode-js-debug ./Land-js-debug
mv ./vscode-js-debug-browsers ./Land-js-debug-browsers
mv ./vscode-js-debug-companion ./Land-js-debug-companion
mv ./vscode-js-profile-visualizer ./Land-js-profile-visualizer
mv ./vscode-jscs ./Land-jscs
mv ./vscode-jshint ./Land-jshint
mv ./vscode-json-languageservice ./Land-json-languageservice
mv ./vscode-JSON.tmLanguage ./Land-JSON.tmLanguage
mv ./vscode-jupyter ./Land-jupyter
mv ./vscode-jupyter-cell-tags ./Land-jupyter-cell-tags
mv ./vscode-jupyter-hub ./Land-jupyter-hub
mv ./vscode-jupyter-ipywidgets ./Land-jupyter-ipywidgets
mv ./vscode-jupyter-keymap ./Land-jupyter-keymap
mv ./vscode-jupyter-lsp-middleware ./Land-jupyter-lsp-middleware
mv ./vscode-jupyter-powertoys ./Land-jupyter-powertoys
mv ./vscode-jupyter-slideshow ./Land-jupyter-slideshow
mv ./vscode-jvm-tools ./Land-jvm-tools
mv ./vscode-l10n ./Land-l10n
mv ./vscode-languagedetection ./Land-languagedetection
mv ./vscode-languageserver-node ./Land-languageserver-node
mv ./vscode-languageserver-protocol-foldingprovider ./Land-languageserver-protocol-foldingprovider
mv ./vscode-LaTeX ./Land-LaTeX
mv ./vscode-linux-build-agent ./Land-linux-build-agent
mv ./vscode-livepreview ./Land-livepreview
mv ./vscode-loader ./Land-loader
mv ./vscode-loc ./Land-loc
mv ./vscode-loc-deprecated ./Land-loc-deprecated
mv ./vscode-lombok ./Land-lombok
mv ./vscode-lsif-extension ./Land-lsif-extension
mv ./vscode-makecode ./Land-makecode
mv ./vscode-makefile-tools ./Land-makefile-tools
mv ./vscode-markdown-it-katex ./Land-markdown-it-katex
mv ./vscode-markdown-languageservice ./Land-markdown-languageservice
mv ./vscode-markdown-notebook ./Land-markdown-notebook
mv ./vscode-markdown-tm-grammar ./Land-markdown-tm-grammar
mv ./vscode-maven ./Land-maven
mv ./vscode-MDTools ./Land-MDTools
mv ./vscode-mezzurite ./Land-mezzurite
mv ./vscode-minimist ./Land-minimist
mv ./vscode-mock-debug ./Land-mock-debug
mv ./vscode-mongodb ./Land-mongodb
mv ./vscode-mono-debug ./Land-mono-debug
mv ./vscode-mssql ./Land-mssql
mv ./vscode-mypy ./Land-mypy
mv ./vscode-nls ./Land-nls
mv ./vscode-nls-dev ./Land-nls-dev
mv ./vscode-node-azure-pack ./Land-node-azure-pack
mv ./vscode-node-debug ./Land-node-debug
mv ./vscode-node-debug2 ./Land-node-debug2
mv ./vscode-node-sqlite3 ./Land-node-sqlite3
mv ./vscode-nodebook ./Land-nodebook
mv ./vscode-notebook-error-overlay ./Land-notebook-error-overlay
mv ./vscode-notebook-renderer-starter ./Land-notebook-renderer-starter
mv ./vscode-notebook-renderers ./Land-notebook-renderers
mv ./vscode-notebook-testdata ./Land-notebook-testdata
mv ./vscode-notepadplusplus-keybindings ./Land-notepadplusplus-keybindings
mv ./vscode-npm-scripts ./Land-npm-scripts
mv ./vscode-octicons-font ./Land-octicons-font
mv ./vscode-onedrive-browser ./Land-onedrive-browser
mv ./vscode-oniguruma ./Land-oniguruma
mv ./vscode-openssl-prebuilt ./Land-openssl-prebuilt
mv ./vscode-perf ./Land-perf
mv ./vscode-perf-bot ./Land-perf-bot
mv ./vscode-platform-specific-sample ./Land-platform-specific-sample
mv ./vscode-policy-watcher ./Land-policy-watcher
mv ./vscode-postgresql ./Land-postgresql
mv ./vscode-powerquery ./Land-powerquery
mv ./vscode-powerquery-sdk ./Land-powerquery-sdk
mv ./vscode-proxy-agent ./Land-proxy-agent
mv ./vscode-pull-request-github ./Land-pull-request-github
mv ./vscode-pwa-analyzer ./Land-pwa-analyzer
mv ./vscode-pylint ./Land-pylint
mv ./vscode-python ./Land-python
mv ./vscode-python-debugger ./Land-python-debugger
mv ./vscode-python-devicesimulator ./Land-python-devicesimulator
mv ./vscode-python-ds-extension-pack ./Land-python-ds-extension-pack
mv ./vscode-python-installer ./Land-python-installer
mv ./vscode-python-tools-extension-template ./Land-python-tools-extension-template
mv ./vscode-python-web-wasm ./Land-python-web-wasm
mv ./vscode-react-native ./Land-react-native
mv ./vscode-react-sample ./Land-react-sample
mv ./vscode-recipes ./Land-recipes
mv ./vscode-references-view ./Land-references-view
mv ./vscode-remote-release ./Land-remote-release
mv ./vscode-remote-repositories-github ./Land-remote-repositories-github
mv ./vscode-remote-try-cpp ./Land-remote-try-cpp
mv ./vscode-remote-try-dotnet ./Land-remote-try-dotnet
mv ./vscode-remote-try-go ./Land-remote-try-go
mv ./vscode-remote-try-java ./Land-remote-try-java
mv ./vscode-remote-try-node ./Land-remote-try-node
mv ./vscode-remote-try-php ./Land-remote-try-php
mv ./vscode-remote-try-python ./Land-remote-try-python
mv ./vscode-remote-try-rust ./Land-remote-try-rust
mv ./vscode-remote-try-sqlserver ./Land-remote-try-sqlserver
mv ./vscode-remote-wsl-recommender ./Land-remote-wsl-recommender
mv ./vscode-resharper-keybindings ./Land-resharper-keybindings
mv ./vscode-ripgrep ./Land-ripgrep
mv ./vscode-russh ./Land-russh
mv ./vscode-samples ./Land-samples
mv ./vscode-SCMBuilders ./Land-SCMBuilders
mv ./vscode-secret-service-rs ./Land-secret-service-rs
mv ./vscode-selfhost-test-provider ./Land-selfhost-test-provider
mv ./vscode-serial-monitor ./Land-serial-monitor
mv ./vscode-service-fabric-reliable-services ./Land-service-fabric-reliable-services
mv ./vscode-service-status ./Land-service-status
mv ./vscode-simple-jupyter-notebook ./Land-simple-jupyter-notebook
mv ./vscode-smoketest-check ./Land-smoketest-check
mv ./vscode-smoketest-express ./Land-smoketest-express
mv ./vscode-spell-check ./Land-spell-check
mv ./vscode-spring-boot-dashboard ./Land-spring-boot-dashboard
mv ./vscode-spring-initializr ./Land-spring-initializr
mv ./vscode-stac ./Land-stac
mv ./vscode-sublime-keybindings ./Land-sublime-keybindings
mv ./vscode-tas-angular ./Land-tas-angular
mv ./vscode-tas-express ./Land-tas-express
mv ./vscode-tas-vue ./Land-tas-vue
mv ./vscode-team ./Land-team
mv ./vscode-telemetry-extractor ./Land-telemetry-extractor
mv ./vscode-tensorboard ./Land-tensorboard
mv ./vscode-test ./Land-test
mv ./vscode-test-adapter-converter ./Land-test-adapter-converter
mv ./vscode-test-cli ./Land-test-cli
mv ./vscode-test-web ./Land-test-web
mv ./vscode-textbuffer ./Land-textbuffer
mv ./vscode-textmate ./Land-textmate
mv ./vscode-theme-color-consumer ./Land-theme-color-consumer
mv ./vscode-theme-tester ./Land-theme-tester
mv ./vscode-themes ./Land-themes
mv ./vscode-tips-and-tricks ./Land-tips-and-tricks
mv ./vscode-tmdl ./Land-tmdl
mv ./vscode-tools-for-ai ./Land-tools-for-ai
mv ./vscode-ts-package-manager ./Land-ts-package-manager
mv ./vscode-ts-tslint ./Land-ts-tslint
mv ./vscode-tslint ./Land-tslint
mv ./vscode-tye ./Land-tye
mv ./vscode-typescript-next ./Land-typescript-next
mv ./vscode-typescript-tslint-plugin ./Land-typescript-tslint-plugin
mv ./vscode-uri ./Land-uri
mv ./vscode-v8-heap-tools ./Land-v8-heap-tools
mv ./vscode-vs-keybindings ./Land-vs-keybindings
mv ./vscode-vsce ./Land-vsce
mv ./vscode-wasm ./Land-wasm
mv ./vscode-web-playground ./Land-web-playground
mv ./vscode-webview-ui-toolkit ./Land-webview-ui-toolkit
mv ./vscode-webview-ui-toolkit-samples ./Land-webview-ui-toolkit-samples
mv ./vscode-wiki ./Land-wiki
mv ./vscode-win32-app-container-tokens ./Land-win32-app-container-tokens
mv ./vscode-windows-ca-certs ./Land-windows-ca-certs
mv ./vscode-windows-process-tree ./Land-windows-process-tree
mv ./vscode-windows-registry ./Land-windows-registry
mv ./vscode-winsta11er ./Land-winsta11er
mv ./vscode-wordcount ./Land-wordcount
mv ./vscode-zeromq ./Land-zeromq
mv ./vscodespaces-quickstart ./Landspaces-quickstart
mv ./vscodetestcover ./Landtestcover
